-- ==========================================================
-- Abinash Catering — Real Menu Seed Data
-- Transcribed directly from the physical Abinash Catering menu
-- card (2 images: dinner menus 1-6, breakfast 1-3, lunch 1-2,
-- the non-veg "காரைக்குழ சமையல்" set, and the add-on services list).
--
-- Run AFTER schema.sql. Safe to re-run: upserts on
-- (menu_section, name_tamil), so it will never duplicate rows.
--
-- NOTE ON ITEM #9 of "டின்னர் மெனு - 1":
-- One dish name on the physical card was not legible enough to
-- transcribe with confidence (glare/blur on the printed card).
-- It has been inserted with is_available = false and a review
-- note so it does not show on the live site until the owner
-- confirms the correct name and flips it to available.
--
-- ENGLISH NAMES:
-- The `name` column has been filled in with English translations of
-- every legible dish (the one exception above stays blank). Confirm
-- these are correct before publishing — in particular, every dish in
-- "காரைக்குழ சமையல்" is prefixed "சைவ" ("veg") on the physical card even
-- though the dishes themselves are fish/prawn/crab/meat items; that
-- prefix has been dropped from the English name rather than guessed at.
-- ==========================================================

insert into menu_items
  (name, name_tamil, description, category, menu_section, image_url, is_available, display_order)
values
  ('Welcome Drinks', 'வெல்கம் டிரிங்ஸ்', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 1),
  ('Cutlet', 'கட்லெட்', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 2),
  ('Gobi 65', 'கோபி - 65', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 3),
  ('Rasmalai', 'ரசமலாய்', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 4),
  ('Mushroom Biryani', 'மஸ்ரூம் பிரியாணி', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 5),
  ('Onion Raita', 'ஆனியன் ரைத்தா', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 6),
  ('Rumali Roti', 'ருமாலி ரொட்டி', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 7),
  ('Paneer Butter Masala', 'பன்னீர் பட்டர் மசாலா', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 8),
  ('', 'ஹறார்ழன் இட்லி', 'Needs verification against the physical menu card — glare/blur made this name illegible.', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', false, 9),
  ('Spicy Chutney', 'கார சட்னி', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 10),
  ('Mini Uthappam', 'மினி ஊத்தப்பம்', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 11),
  ('Sambar', 'சாம்பார்', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 12),
  ('Sambar Rice', 'சாம்பார் சாதம்', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 13),
  ('Curd Rice', 'தயிர் சாதம்', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 14),
  ('Omelette Rice', 'ஓமிட் ரைஸ்', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 15),
  ('Rasam', 'ரசம்', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 16),
  ('Potato Chips', 'உருளை சாப்ஸ்', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 17),
  ('Kadamba Kootu', 'கதம்ப கூட்டு', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 18),
  ('Samba Wheat Payasam', 'சம்பா கோதுமை பாயாசம்', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 19),
  ('Pickle', 'ஊறுகாய்', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 20),
  ('Ice Cream', 'ICE கிரீம்', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 21),
  ('Water Bottle', 'வாட்டர் பாட்டில்', '', 'Dinner', 'டின்னர் மெனு - 1', '/static/images/food/placeholder.jpg', true, 22),
  ('Welcome Drinks', 'வெல்கம் டிரிங்ஸ்', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 1),
  ('Kaju Katli Sweet', 'காஜி கத்திலி ஸ்வீட்', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 2),
  ('Veg Lollipop', 'வெஜ் லாலி பாப்', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 3),
  ('Onion Bajji', 'ஆனியன் பக்கோடா', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 4),
  ('Jackfruit Biryani', 'பலா பிரியாணி', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 5),
  ('Onion Raita', 'ஆனியன் ரைத்தா', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 6),
  ('Butter Naan', 'பட்டர் நான்', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 7),
  ('Baby Corn Gravy', 'பேபிகார்ன் கிரேவி', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 8),
  ('Idiyappam', 'இடியாப்பம்', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 9),
  ('Veg Kurma', 'வெஜ் குருமா', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 10),
  ('Masala Dosai', 'மசால் தோசை', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 11),
  ('Sambar', 'சாம்பார்', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 12),
  ('Omelette Rice', 'ஓமிட் ரைஸ்', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 13),
  ('Vatha Kuzhambu', 'வத்த குழம்பு', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 14),
  ('Rasam', 'ரசம்', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 15),
  ('Elephant Yam Chips', 'கருனை கிழங்கு சாப்ஸ்', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 16),
  ('Poriyal (Vegetable Stir-fry)', 'தேசிய பொறியல்', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 17),
  ('Tender Coconut Payasam', 'இளநீர் பாயாசம்', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 18),
  ('Appalam', 'அப்பளம்', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 19),
  ('Pickle', 'ஊறுகாய்', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 20),
  ('Ice Cream', 'ICE கிரீம்', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 21),
  ('Water Bottle', 'வாட்டர் பாட்டில்', '', 'Dinner', 'டின்னர் மெனு - 2', '/static/images/food/placeholder.jpg', true, 22),
  ('Welcome Drinks', 'வெல்கம் டிரிங்ஸ்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 1),
  ('Paan (Betel Leaf)', 'பீடா', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 2),
  ('Spring Roll', 'ஸ்பிரிங் ரோல்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 3),
  ('Medu Bajji', 'மெது பக்கோடா', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 4),
  ('Rumali Roti', 'ரூமாலி ரொட்டு', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 5),
  ('Mushroom Pepper Masala', 'மஸ்ரூம் பெப்பர் மசாலா', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 6),
  ('Veg Pulao', 'வெஜ் புலாவ்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 7),
  ('Onion Raita', 'ஆனியன் ரைத்தா', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 8),
  ('Mini Idli', 'மினி இட்லி', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 9),
  ('Sambar', 'சாம்பார்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 10),
  ('Sambar Rice', 'சாம்பார் சாதம்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 11),
  ('Vatha Kuzhambu Rice', 'வத்த குழம்பு சாதம்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 12),
  ('Omelette Rice', 'ஓயிட் ரைஸ்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 13),
  ('Curd Rice', 'தயிர் சாதம்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 14),
  ('Rasam', 'ரசம்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 15),
  ('Yam Chips', 'சேனை சாப்ஸ்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 16),
  ('Poriyal (Vegetable Stir-fry)', 'தேசிய பொறியல்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 17),
  ('Foxtail Millet Payasam', 'தினை அரிசி பாயாசம்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 18),
  ('Appalam', 'அப்பளம்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 19),
  ('Pickle', 'ஊறுகாய்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 20),
  ('Ice Cream', 'ICE கிரீம்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 21),
  ('Water Bottle', 'வாட்டர் பாட்டில்', '', 'Dinner', 'டின்னர் மெனு - 3', '/static/images/food/placeholder.jpg', true, 22),
  ('Welcome Drinks', 'வெல்கம் டிரிங்ஸ்', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 1),
  ('Almond Halwa', 'பாதாம் அல்வா', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 2),
  ('Paneer 65', 'பன்னீர் - 65', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 3),
  ('Chapati', 'சப்பாத்தி', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 4),
  ('Sweet Corn Gravy', 'ஸ்வீட் கார்ன் கிரேவி', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 5),
  ('Veg Pulao', 'வெஜ் புலாவ்', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 6),
  ('Onion Raita', 'ஆனியன் ரைத்தா', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 7),
  ('Kuzhi Paniyaram', 'குழி பனியாரம்', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 8),
  ('Spicy Chutney', 'கார சட்னி', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 9),
  ('Podi Dosai', 'பொடி தோசை', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 10),
  ('Mint Chutney', 'புதினா சட்னி', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 11),
  ('Idiyappam', 'இடியாப்பம்', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 12),
  ('White Kurma', 'ஓயிட் குருமா', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 13),
  ('Omelette Rice', 'ஓயிட் ரைஸ்', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 14),
  ('Rasam', 'ரசம்', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 15),
  ('Potato Fry', 'உருளை வறுவல்', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 16),
  ('Chips', 'சிப்ஸ்', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 17),
  ('Pickle', 'ஊறுகாய்', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 18),
  ('Cream', 'கிரீம்', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 19),
  ('Water Bottle', 'வாட்டர் பாட்டில்', '', 'Dinner', 'டின்னர் மெனு - 4', '/static/images/food/placeholder.jpg', true, 20),
  ('Welcome Drinks', 'வெல்கம் டிரிங்ஸ்', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 1),
  ('Gulab Jamun', 'குளோப் ஜாமுன்', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 2),
  ('Chapati', 'சப்பாத்தி', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 3),
  ('Chana Masala', 'சென்னா மசாலா', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 4),
  ('Veg Pulao', 'வெஜ்புலாவ்', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 5),
  ('Onion Raita', 'ஆனியன் ரைத்தா', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 6),
  ('Omelette Rice', 'ஓயிட் ரைஸ்', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 7),
  ('Sambar', 'சாம்பார்', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 8),
  ('Vatha Kuzhambu', 'வத்த குழம்பு', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 9),
  ('Rasam', 'ரசம்', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 10),
  ('Buttermilk', 'மோர்', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 11),
  ('Potato Fry', 'உருளை வறுவல்', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 12),
  ('Poriyal (Vegetable Stir-fry)', 'தேசிய பொறியல்', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 13),
  ('Medu Vada', 'மெதுவடை', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 14),
  ('Appalam', 'அப்பளம்', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 15),
  ('Pickle', 'ஊறுகாய்', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 16),
  ('Ice Cream', 'ICE கிரீம்', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 17),
  ('Water Bottle', 'வாட்டர்பாட்டில்', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 18),
  ('Milk Payasam', 'பால்பாயாசம்', '', 'Dinner', 'டின்னர் மெனு - 5', '/static/images/food/placeholder.jpg', true, 19),
  ('Welcome Drinks', 'வெல்கம் டிரிங்ஸ்', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 1),
  ('Pista Cake', 'பிஸ்தா கேக்', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 2),
  ('Medu Bajji', 'மெதுபக்கோடா', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 3),
  ('Bun Parotta', 'பன் பரோட்டா', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 4),
  ('Gobi Manchurian (or) Veg Kurma', 'கோபி மஞ்சூரியன் (அ) வெஜ்குருமா', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 5),
  ('Noodles', 'நூடுல்ஸ்', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 6),
  ('Lemon Sevai (Lemon Rice)', 'லெமன் சேவை', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 7),
  ('Masala Dosai', 'மசால் தோசை', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 8),
  ('Sambar', 'சாம்பார்', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 9),
  ('Sambar Rice', 'சாம்பார் சாதம்', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 10),
  ('Curd Rice', 'தயிர் சாதம்', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 11),
  ('Omelette Rice', 'ஓயிட் ரைஸ்', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 12),
  ('Vatha Kuzhambu', 'வத்த குழம்பு', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 13),
  ('Rasam', 'ரசம்', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 14),
  ('Elephant Yam Chips', 'கருனை கிழங்கு சாப்ஸ்', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 15),
  ('Kadamba Kootu', 'கதம்ப கூட்டு', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 16),
  ('Palm Fruit (Nungu) Payasam', 'நுங்கு பாயாசம்', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 17),
  ('Appalam', 'அப்பளம்', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 18),
  ('Pickle', 'ஊறுகாய்', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 19),
  ('Water Bottle', 'வாட்டர் பாட்டில்', '', 'Dinner', 'டின்னர் மெனு - 6', '/static/images/food/placeholder.jpg', true, 20),
  ('Morning Bed Coffee', 'காலை பெட் காபி', '', 'Breakfast', 'காலை டிபன் - 1', '/static/images/food/placeholder.jpg', true, 1),
  ('Kasi Halwa', 'காசி அல்வா', '', 'Breakfast', 'காலை டிபன் - 1', '/static/images/food/placeholder.jpg', true, 2),
  ('Malli Poo Idli', 'மல்லி பூ இட்லி', '', 'Breakfast', 'காலை டிபன் - 1', '/static/images/food/placeholder.jpg', true, 3),
  ('Ghee Pongal', 'நெய் பொங்கல்', '', 'Breakfast', 'காலை டிபன் - 1', '/static/images/food/placeholder.jpg', true, 4),
  ('Palak (Spinach) Poori', 'பாலக்கீரை பூரி', '', 'Breakfast', 'காலை டிபன் - 1', '/static/images/food/placeholder.jpg', true, 5),
  ('Kizhangu Curry', 'கிழங்கு', '', 'Breakfast', 'காலை டிபன் - 1', '/static/images/food/placeholder.jpg', true, 6),
  ('Set Dosai', 'செட் தோசை', '', 'Breakfast', 'காலை டிபன் - 1', '/static/images/food/placeholder.jpg', true, 7),
  ('Vada Curry', 'வடகறி', '', 'Breakfast', 'காலை டிபன் - 1', '/static/images/food/placeholder.jpg', true, 8),
  ('Coconut Chutney', 'தேங்காய் சட்னி', '', 'Breakfast', 'காலை டிபன் - 1', '/static/images/food/placeholder.jpg', true, 9),
  ('Spicy Chutney', 'கார சட்னி', '', 'Breakfast', 'காலை டிபன் - 1', '/static/images/food/placeholder.jpg', true, 10),
  ('Medu Vada', 'மெதுவடை', '', 'Breakfast', 'காலை டிபன் - 1', '/static/images/food/placeholder.jpg', true, 11),
  ('Sambar', 'சாம்பார்', '', 'Breakfast', 'காலை டிபன் - 1', '/static/images/food/placeholder.jpg', true, 12),
  ('Water Bottle', 'வாட்டர் பாட்டில்', '', 'Breakfast', 'காலை டிபன் - 1', '/static/images/food/placeholder.jpg', true, 13),
  ('Morning Bed Coffee', 'காலை பெட் காபி', '', 'Breakfast', 'காலை டிபன் - 2', '/static/images/food/placeholder.jpg', true, 1),
  ('Carrot Halwa', 'கேரட் அல்வா', '', 'Breakfast', 'காலை டிபன் - 2', '/static/images/food/placeholder.jpg', true, 2),
  ('Mini Idli', 'மினி இட்லி', '', 'Breakfast', 'காலை டிபன் - 2', '/static/images/food/placeholder.jpg', true, 3),
  ('Sambar', 'சாம்பார்', '', 'Breakfast', 'காலை டிபன் - 2', '/static/images/food/placeholder.jpg', true, 4),
  ('Rava Kichadi', 'ரவா கிச்சடி', '', 'Breakfast', 'காலை டிபன் - 2', '/static/images/food/placeholder.jpg', true, 5),
  ('Idiyappam', 'இடியாப்பம்', '', 'Breakfast', 'காலை டிபன் - 2', '/static/images/food/placeholder.jpg', true, 6),
  ('White Kurma', 'ஓயிட் குருமா', '', 'Breakfast', 'காலை டிபன் - 2', '/static/images/food/placeholder.jpg', true, 7),
  ('Podi Dosai', 'பொடி தோசை', '', 'Breakfast', 'காலை டிபன் - 2', '/static/images/food/placeholder.jpg', true, 8),
  ('Mint Chutney', 'புதினா சட்னி', '', 'Breakfast', 'காலை டிபன் - 2', '/static/images/food/placeholder.jpg', true, 9),
  ('Coconut Chutney', 'தேங்காய் சட்னி', '', 'Breakfast', 'காலை டிபன் - 2', '/static/images/food/placeholder.jpg', true, 10),
  ('Spicy Chutney', 'கார சட்னி', '', 'Breakfast', 'காலை டிபன் - 2', '/static/images/food/placeholder.jpg', true, 11),
  ('Medu Vada', 'மெதுவடை', '', 'Breakfast', 'காலை டிபன் - 2', '/static/images/food/placeholder.jpg', true, 12),
  ('Sambar', 'சாம்பார்', '', 'Breakfast', 'காலை டிபன் - 2', '/static/images/food/placeholder.jpg', true, 13),
  ('Water Bottle', 'வாட்டர் பாட்டில்', '', 'Breakfast', 'காலை டிபன் - 2', '/static/images/food/placeholder.jpg', true, 14),
  ('Morning Bed Coffee', 'காலை பெட் காபி', '', 'Breakfast', 'காலை டிபன் - 3', '/static/images/food/placeholder.jpg', true, 1),
  ('Bread Halwa', 'பிரெட் அல்வா', '', 'Breakfast', 'காலை டிபன் - 3', '/static/images/food/placeholder.jpg', true, 2),
  ('Rava Pongal', 'ரவா பொங்கல்', '', 'Breakfast', 'காலை டிபன் - 3', '/static/images/food/placeholder.jpg', true, 3),
  ('Mini Poori', 'மினி பூரி', '', 'Breakfast', 'காலை டிபன் - 3', '/static/images/food/placeholder.jpg', true, 4),
  ('Kizhangu Curry', 'கிழங்கு', '', 'Breakfast', 'காலை டிபன் - 3', '/static/images/food/placeholder.jpg', true, 5),
  ('Appam', 'ஆப்பம்', '', 'Breakfast', 'காலை டிபன் - 3', '/static/images/food/placeholder.jpg', true, 6),
  ('Coconut Chutney', 'தேங்காய் சட்னி', '', 'Breakfast', 'காலை டிபன் - 3', '/static/images/food/placeholder.jpg', true, 7),
  ('Peanut Chutney', 'வேர்கடலை சட்னி', '', 'Breakfast', 'காலை டிபன் - 3', '/static/images/food/placeholder.jpg', true, 8),
  ('Medu Bonda', 'மெது போன்டா', '', 'Breakfast', 'காலை டிபன் - 3', '/static/images/food/placeholder.jpg', true, 9),
  ('Sambar', 'சாம்பார்', '', 'Breakfast', 'காலை டிபன் - 3', '/static/images/food/placeholder.jpg', true, 10),
  ('Water Bottle', 'வாட்டர் பாட்டில்', '', 'Breakfast', 'காலை டிபன் - 3', '/static/images/food/placeholder.jpg', true, 11),
  ('Coconut Milk (or) Vada Curry', 'தேங்காய் பால் (அ) வடகறி', '', 'Breakfast', 'காலை டிபன் - 3', '/static/images/food/placeholder.jpg', true, 12),
  ('Paal Paniyaram', 'பால் பணியாரம்', '', 'Non-Vegetarian', 'காரைக்குழ சமையல்', '/static/images/food/placeholder.jpg', true, 1),
  ('Appam', 'ஆப்பம்', '', 'Non-Vegetarian', 'காரைக்குழ சமையல்', '/static/images/food/placeholder.jpg', true, 2),
  ('Double-Colour Idli', 'டபுள் கலர் இட்லி', '', 'Non-Vegetarian', 'காரைக்குழ சமையல்', '/static/images/food/placeholder.jpg', true, 3),
  ('Sea Fish Curry', 'சைவமீன் குழம்பு', '', 'Non-Vegetarian', 'காரைக்குழ சமையல்', '/static/images/food/placeholder.jpg', true, 4),
  ('Anchovy (Nethili) Fish Curry', 'சைவ நெத்திலி மீன் குழம்பு', '', 'Non-Vegetarian', 'காரைக்குழ சமையல்', '/static/images/food/placeholder.jpg', true, 5),
  ('Vanjaram (Seer Fish) Curry', 'சைவ வஞ்ர மீன் குழம்பு', '', 'Non-Vegetarian', 'காரைக்குழ சமையல்', '/static/images/food/placeholder.jpg', true, 6),
  ('Prawn Gravy', 'சைவ இறால் கிரேவி', '', 'Non-Vegetarian', 'காரைக்குழ சமையல்', '/static/images/food/placeholder.jpg', true, 7),
  ('Crab Gravy', 'சைவ போட்டி கிரேவி', '', 'Non-Vegetarian', 'காரைக்குழ சமையல்', '/static/images/food/placeholder.jpg', true, 8),
  ('Prawn Thokku', 'சைவ இறால் தொக்கு', '', 'Non-Vegetarian', 'காரைக்குழ சமையல்', '/static/images/food/placeholder.jpg', true, 9),
  ('Egg Podimas', 'சைவ முட்டை பொடிமாஸ்', '', 'Non-Vegetarian', 'காரைக்குழ சமையல்', '/static/images/food/placeholder.jpg', true, 10),
  ('Vanjaram (Seer Fish) Fry', 'சைவ வஞ்ர மீன் வறுவல்', '', 'Non-Vegetarian', 'காரைக்குழ சமையல்', '/static/images/food/placeholder.jpg', true, 11),
  ('Meat/Fish Ball Curry', 'சைவ உருண்டை குழம்பு', '', 'Non-Vegetarian', 'காரைக்குழ சமையல்', '/static/images/food/placeholder.jpg', true, 12),
  ('Ragi Kali', 'கேழ்வரகு களி', '', 'Non-Vegetarian', 'காரைக்குழ சமையல்', '/static/images/food/placeholder.jpg', true, 13),
  ('Coriander Seed Chutney', 'தனியா சட்னி', '', 'Non-Vegetarian', 'காரைக்குழ சமையல்', '/static/images/food/placeholder.jpg', true, 14),
  ('Gulab Jamun', 'குளோப் ஜாமுன்', '', 'Lunch', 'மதியம் சாப்பாடு - 1', '/static/images/food/placeholder.jpg', true, 1),
  ('Omelette Rice', 'ஓயிட் ரைஸ்', '', 'Lunch', 'மதியம் சாப்பாடு - 1', '/static/images/food/placeholder.jpg', true, 2),
  ('Sambar', 'சாம்பார்', '', 'Lunch', 'மதியம் சாப்பாடு - 1', '/static/images/food/placeholder.jpg', true, 3),
  ('Mor Kuzhambu (Buttermilk Curry)', 'மோர் குழம்பு', '', 'Lunch', 'மதியம் சாப்பாடு - 1', '/static/images/food/placeholder.jpg', true, 4),
  ('Rasam', 'ரசம்', '', 'Lunch', 'மதியம் சாப்பாடு - 1', '/static/images/food/placeholder.jpg', true, 5),
  ('Avial', 'அவியல்', '', 'Lunch', 'மதியம் சாப்பாடு - 1', '/static/images/food/placeholder.jpg', true, 6),
  ('Varuval (Dry Fry)', 'வறுவல்', '', 'Lunch', 'மதியம் சாப்பாடு - 1', '/static/images/food/placeholder.jpg', true, 7),
  ('Medu Vada', 'மெதுவடை', '', 'Lunch', 'மதியம் சாப்பாடு - 1', '/static/images/food/placeholder.jpg', true, 8),
  ('Malabar Payasam', 'மலபார் பாயாசம்', '', 'Lunch', 'மதியம் சாப்பாடு - 1', '/static/images/food/placeholder.jpg', true, 9),
  ('Appalam', 'அப்பளம்', '', 'Lunch', 'மதியம் சாப்பாடு - 1', '/static/images/food/placeholder.jpg', true, 10),
  ('Pickle', 'ஊறுகாய்', '', 'Lunch', 'மதியம் சாப்பாடு - 1', '/static/images/food/placeholder.jpg', true, 11),
  ('Water Bottle', 'வாட்டர் பாட்டில்', '', 'Lunch', 'மதியம் சாப்பாடு - 1', '/static/images/food/placeholder.jpg', true, 12),
  ('Gulab Jamun', 'குளோப் ஜாமுன்', '', 'Lunch', 'மதியம் சாப்பாடு - 2', '/static/images/food/placeholder.jpg', true, 1),
  ('Veg Pulao', 'வெஜ் புலாவ்', '', 'Lunch', 'மதியம் சாப்பாடு - 2', '/static/images/food/placeholder.jpg', true, 2),
  ('Onion Raita', 'ஆனியன் ரைத்தா', '', 'Lunch', 'மதியம் சாப்பாடு - 2', '/static/images/food/placeholder.jpg', true, 3),
  ('Omelette Rice', 'ஓயிட் ரைஸ்', '', 'Lunch', 'மதியம் சாப்பாடு - 2', '/static/images/food/placeholder.jpg', true, 4),
  ('Sambar', 'சாம்பார்', '', 'Lunch', 'மதியம் சாப்பாடு - 2', '/static/images/food/placeholder.jpg', true, 5),
  ('Vatha Kuzhambu', 'வத்த குழம்பு', '', 'Lunch', 'மதியம் சாப்பாடு - 2', '/static/images/food/placeholder.jpg', true, 6),
  ('Rasam', 'ரசம்', '', 'Lunch', 'மதியம் சாப்பாடு - 2', '/static/images/food/placeholder.jpg', true, 7),
  ('Buttermilk', 'மோர்', '', 'Lunch', 'மதியம் சாப்பாடு - 2', '/static/images/food/placeholder.jpg', true, 8),
  ('Poriyal (Vegetable Stir-fry)', 'தேசிய பொறியல்', '', 'Lunch', 'மதியம் சாப்பாடு - 2', '/static/images/food/placeholder.jpg', true, 9),
  ('Kadamba Kootu', 'கதம்ப கூட்டு', '', 'Lunch', 'மதியம் சாப்பாடு - 2', '/static/images/food/placeholder.jpg', true, 10),
  ('Vadai', 'வடை', '', 'Lunch', 'மதியம் சாப்பாடு - 2', '/static/images/food/placeholder.jpg', true, 11),
  ('Payasam', 'பாயாசம்', '', 'Lunch', 'மதியம் சாப்பாடு - 2', '/static/images/food/placeholder.jpg', true, 12),
  ('Appalam', 'அப்பளம்', '', 'Lunch', 'மதியம் சாப்பாடு - 2', '/static/images/food/placeholder.jpg', true, 13),
  ('Pickle', 'ஊறுகாய்', '', 'Lunch', 'மதியம் சாப்பாடு - 2', '/static/images/food/placeholder.jpg', true, 14),
  ('Water Bottle', 'வாட்டர் பாட்டில்', '', 'Lunch', 'மதியம் சாப்பாடு - 2', '/static/images/food/placeholder.jpg', true, 15),
  ('Popcorn', 'பாப்கார்ன்', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 1),
  ('Cotton Candy', 'பஞ்சு மிட்டாய்', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 2),
  ('Name Balloon', 'பெயர் பலூன்', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 3),
  ('Welcome Set', 'வரவேற்பு செட்', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 4),
  ('Mickey Mouse', 'மிக்கி மவுஸ்', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 5),
  ('Chocolate Fountain', 'சாக்லெட் பவுண்டன்', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 6),
  ('Tattoos', 'டாட்டூஸ்', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 7),
  ('Mehendi (Henna)', 'மெகந்தி', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 8),
  ('Aarti Plate', 'ஆரத்தி தட்டு', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 9),
  ('Welcome Girls', 'வரவேற்பு பெண்கள்', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 10),
  ('Jumping (Bouncy Castle)', 'ஜம்பிங்', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 11),
  ('Bangles', 'வளையல்', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 12),
  ('Flower-Scattering Girls', 'பூ தூவும் பெண்கள்', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 13),
  ('Smoke Paan', 'ஸ்மோக் பீடா', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 14),
  ('Smoke Biscuit', 'ஸ்மோக் பிஸ்கட்', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 15),
  ('Jelly Candy', 'ஜவ்வு மிட்டாய்', '', 'Services', 'விசேஷ சேவைகள் (Additional Services)', '/static/images/food/placeholder.jpg', true, 16)
on conflict (menu_section, name_tamil) do update set
  name = excluded.name,
  category = excluded.category,
  display_order = excluded.display_order;

